import { StyleSheet } from "react-native";

export const Farver = {
  baggrund: "#f4f7f2",
  kort: "#ffffff",
  primær: "#2f6f4e",
  sekundær: "#d7eadf",
  tekst: "#152018",
  muted: "#68756d",
  kant: "#dce5dd",
  alarm: "#b42318",
};

export const GS = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Farver.baggrund,
  },
  screen: {
    padding: 16,
    gap: 14,
  },
  homeScreen: {
    flexGrow: 1,
    justifyContent: "center",
    padding: 18,
    gap: 18,
  },
  center: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  simpleListScreen: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    backgroundColor: "#eaf3ec",
  },
  simpleListBox: {
    height: 280,
    backgroundColor: "#f8fbf8",
    borderColor: "#bad5c1",
    borderWidth: 1,
    borderRadius: 8,
    width: "90%",
    marginTop: 14,
    padding: 8,
  },
  simpleListItem: {
    color: Farver.tekst,
    fontSize: 15,
    padding: 12,
    textAlign: "center",
  },
  profileListItem: {
    backgroundColor: "#ffffff",
    borderLeftColor: Farver.primær,
    borderLeftWidth: 5,
    borderRadius: 8,
    padding: 12,
    marginBottom: 10,
  },
  profileListTitle: {
    color: Farver.tekst,
    fontSize: 16,
    fontWeight: "800",
    marginBottom: 4,
  },
  profileListMeta: {
    color: Farver.muted,
    marginBottom: 6,
  },
  profileListPrice: {
    color: Farver.primær,
    fontSize: 16,
    fontWeight: "800",
  },
  hero: {
    backgroundColor: Farver.primær,
    borderRadius: 8,
    padding: 22,
    minHeight: 210,
    justifyContent: "center",
  },
  heroTitle: {
    color: "#ffffff",
    fontSize: 34,
    fontWeight: "800",
    marginBottom: 8,
    textAlign: "center",
  },
  heroText: {
    color: "#edf7f0",
    fontSize: 16,
    lineHeight: 22,
    textAlign: "center",
  },
  heroStatRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 20,
  },
  heroStat: {
    flex: 1,
    backgroundColor: "rgba(255, 255, 255, 0.14)",
    borderRadius: 8,
    padding: 12,
    alignItems: "center",
  },
  heroStatNumber: {
    color: "#ffffff",
    fontSize: 20,
    fontWeight: "800",
  },
  heroStatLabel: {
    color: "#edf7f0",
    fontSize: 12,
    textAlign: "center",
    marginTop: 4,
  },
  homeIntro: {
    alignItems: "center",
    paddingHorizontal: 4,
  },
  title: {
    fontSize: 24,
    fontWeight: "800",
    color: Farver.tekst,
    textAlign: "center",
  },
  subtitle: {
    fontSize: 16,
    color: Farver.muted,
    lineHeight: 22,
    textAlign: "center",
  },
  sectionTitle: {
    color: Farver.tekst,
    fontSize: 18,
    fontWeight: "800",
    marginTop: 4,
    marginBottom: 4,
  },
  featureGrid: {
    gap: 10,
  },
  featureCard: {
    backgroundColor: Farver.kort,
    borderColor: Farver.kant,
    borderWidth: 1,
    borderRadius: 8,
    padding: 14,
  },
  featureIcon: {
    color: Farver.primær,
    fontWeight: "800",
    marginBottom: 6,
  },
  featureTitle: {
    color: Farver.tekst,
    fontSize: 16,
    fontWeight: "800",
    marginBottom: 4,
  },
  featureText: {
    color: Farver.muted,
    lineHeight: 20,
  },
  card: {
    backgroundColor: Farver.kort,
    borderColor: Farver.kant,
    borderWidth: 1,
    borderRadius: 8,
    padding: 14,
    marginBottom: 12,
  },
  listingImage: {
    width: "100%",
    height: 135,
    borderRadius: 8,
    marginBottom: 10,
    backgroundColor: Farver.sekundær,
  },
  detailsImage: {
    width: "100%",
    height: 240,
    borderRadius: 8,
    backgroundColor: Farver.sekundær,
  },
  cardTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: Farver.tekst,
    marginBottom: 4,
  },
  meta: {
    color: Farver.muted,
    marginBottom: 6,
  },
  price: {
    fontSize: 18,
    fontWeight: "800",
    color: Farver.primær,
  },
  row: {
    marginBottom: 12,
  },
  label: {
    color: Farver.tekst,
    fontWeight: "700",
    marginBottom: 6,
  },
  input: {
    backgroundColor: Farver.kort,
    borderColor: Farver.kant,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  button: {
    backgroundColor: Farver.primær,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: "center",
  },
  buttonText: {
    color: "#ffffff",
    fontWeight: "800",
  },
});
